<?php

use Illuminate\Database\Seeder;

class PaisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('paises')->insert(['codigo_iso2' => 'BR', 'codigo_iso3' => 'BRA', 'nome' => 'Brasil', 'codigo_fone' => '55']);
        DB::table('paises')->insert(['codigo_iso2' => 'AF', 'codigo_iso3' => 'AFG', 'nome' => 'Afeganistão', 'codigo_fone' => '93']);
		DB::table('paises')->insert(['codigo_iso2' => 'AL', 'codigo_iso3' => 'ALB', 'nome' => 'Albânia', 'codigo_fone' => '355']);
		DB::table('paises')->insert(['codigo_iso2' => 'DZ', 'codigo_iso3' => 'DZA', 'nome' => 'Algéria', 'codigo_fone' => '213']);
		DB::table('paises')->insert(['codigo_iso2' => 'AS', 'codigo_iso3' => 'ASM', 'nome' => 'Samoa Americana', 'codigo_fone' => '1684']);
		DB::table('paises')->insert(['codigo_iso2' => 'AD', 'codigo_iso3' => 'AND', 'nome' => 'Andorra', 'codigo_fone' => '376']);
		DB::table('paises')->insert(['codigo_iso2' => 'AO', 'codigo_iso3' => 'AGO', 'nome' => 'Angola', 'codigo_fone' => '244']);
		DB::table('paises')->insert(['codigo_iso2' => 'AI', 'codigo_iso3' => 'AIA', 'nome' => 'Anguilla', 'codigo_fone' => '1264']);
		DB::table('paises')->insert(['codigo_iso2' => 'AQ', 'codigo_iso3' => 'ATA', 'nome' => 'Antártida', 'codigo_fone' => '672']);
		DB::table('paises')->insert(['codigo_iso2' => 'AG', 'codigo_iso3' => 'ATG', 'nome' => 'Antigua e Barbuda', 'codigo_fone' => '1268']);
		DB::table('paises')->insert(['codigo_iso2' => 'AR', 'codigo_iso3' => 'ARG', 'nome' => 'Argentina', 'codigo_fone' => '54']);
		DB::table('paises')->insert(['codigo_iso2' => 'AM', 'codigo_iso3' => 'ARM', 'nome' => 'Armênia', 'codigo_fone' => '374']);
		DB::table('paises')->insert(['codigo_iso2' => 'AW', 'codigo_iso3' => 'ABW', 'nome' => 'Aruba', 'codigo_fone' => '297']);
		DB::table('paises')->insert(['codigo_iso2' => 'AU', 'codigo_iso3' => 'AUS', 'nome' => 'Austrália', 'codigo_fone' => '61']);
		DB::table('paises')->insert(['codigo_iso2' => 'AT', 'codigo_iso3' => 'AUT', 'nome' => 'Áustria', 'codigo_fone' => '43']);
		DB::table('paises')->insert(['codigo_iso2' => 'AZ', 'codigo_iso3' => 'AZE', 'nome' => 'Azerbaijão', 'codigo_fone' => '994']);
		DB::table('paises')->insert(['codigo_iso2' => 'BS', 'codigo_iso3' => 'BHS', 'nome' => 'Bahamas', 'codigo_fone' => '1242']);
		DB::table('paises')->insert(['codigo_iso2' => 'BH', 'codigo_iso3' => 'BHR', 'nome' => 'Bahrein', 'codigo_fone' => '973']);
		DB::table('paises')->insert(['codigo_iso2' => 'BD', 'codigo_iso3' => 'BGD', 'nome' => 'Bangladesh', 'codigo_fone' => '880']);
		DB::table('paises')->insert(['codigo_iso2' => 'BB', 'codigo_iso3' => 'BRB', 'nome' => 'Barbados', 'codigo_fone' => '246']);
		DB::table('paises')->insert(['codigo_iso2' => 'BY', 'codigo_iso3' => 'BLR', 'nome' => 'Bielorrússia', 'codigo_fone' => '375']);
		DB::table('paises')->insert(['codigo_iso2' => 'BE', 'codigo_iso3' => 'BEL', 'nome' => 'Bélgica', 'codigo_fone' => '32']);
		DB::table('paises')->insert(['codigo_iso2' => 'BZ', 'codigo_iso3' => 'BLZ', 'nome' => 'Belize', 'codigo_fone' => '501']);
		DB::table('paises')->insert(['codigo_iso2' => 'BJ', 'codigo_iso3' => 'BEN', 'nome' => 'Benin', 'codigo_fone' => '229']);
		DB::table('paises')->insert(['codigo_iso2' => 'BM', 'codigo_iso3' => 'BMU', 'nome' => 'Bermuda', 'codigo_fone' => '1441']);
		DB::table('paises')->insert(['codigo_iso2' => 'BT', 'codigo_iso3' => 'BTN', 'nome' => 'Butão', 'codigo_fone' => '975']);
		DB::table('paises')->insert(['codigo_iso2' => 'BO', 'codigo_iso3' => 'BOL', 'nome' => 'Bolívia', 'codigo_fone' => '591']);
		DB::table('paises')->insert(['codigo_iso2' => 'BA', 'codigo_iso3' => 'BIH', 'nome' => 'Bósnia e Herzegovina', 'codigo_fone' => '387']);
		DB::table('paises')->insert(['codigo_iso2' => 'BW', 'codigo_iso3' => 'BWA', 'nome' => 'Botswana', 'codigo_fone' => '267']);
		DB::table('paises')->insert(['codigo_iso2' => 'BV', 'codigo_iso3' => 'BVT', 'nome' => 'Ilha Bouvet', 'codigo_fone' => '47']);
		DB::table('paises')->insert(['codigo_iso2' => 'IO', 'codigo_iso3' => 'IOT', 'nome' => 'Território Britânico do Oceano Índico', 'codigo_fone' => '246']);
		DB::table('paises')->insert(['codigo_iso2' => 'BN', 'codigo_iso3' => 'BRN', 'nome' => 'Brunei', 'codigo_fone' => '673']);
		DB::table('paises')->insert(['codigo_iso2' => 'BG', 'codigo_iso3' => 'BGR', 'nome' => 'Bulgária', 'codigo_fone' => '359']);
		DB::table('paises')->insert(['codigo_iso2' => 'BF', 'codigo_iso3' => 'BFA', 'nome' => 'Burkina Faso', 'codigo_fone' => '226']);
		DB::table('paises')->insert(['codigo_iso2' => 'BI', 'codigo_iso3' => 'BDI', 'nome' => 'Burundi', 'codigo_fone' => '257']);
		DB::table('paises')->insert(['codigo_iso2' => 'KH', 'codigo_iso3' => 'KHM', 'nome' => 'Camboja', 'codigo_fone' => '855']);
		DB::table('paises')->insert(['codigo_iso2' => 'CM', 'codigo_iso3' => 'CMR', 'nome' => 'Camarões', 'codigo_fone' => '237']);
		DB::table('paises')->insert(['codigo_iso2' => 'CA', 'codigo_iso3' => 'CAN', 'nome' => 'Canadá', 'codigo_fone' => '1']);
		DB::table('paises')->insert(['codigo_iso2' => 'CV', 'codigo_iso3' => 'CPV', 'nome' => 'Cabo Verde', 'codigo_fone' => '238']);
		DB::table('paises')->insert(['codigo_iso2' => 'KY', 'codigo_iso3' => 'CYM', 'nome' => 'Ilhas Cayman', 'codigo_fone' => '1345']);
		DB::table('paises')->insert(['codigo_iso2' => 'CF', 'codigo_iso3' => 'CAF', 'nome' => 'República Centro-Africana', 'codigo_fone' => '236']);
		DB::table('paises')->insert(['codigo_iso2' => 'TD', 'codigo_iso3' => 'TCD', 'nome' => 'Chade', 'codigo_fone' => '235']);
		DB::table('paises')->insert(['codigo_iso2' => 'CL', 'codigo_iso3' => 'CHL', 'nome' => 'Chile', 'codigo_fone' => '56']);
		DB::table('paises')->insert(['codigo_iso2' => 'CN', 'codigo_iso3' => 'CHN', 'nome' => 'China', 'codigo_fone' => '86']);
		DB::table('paises')->insert(['codigo_iso2' => 'CX', 'codigo_iso3' => 'CXR', 'nome' => 'Ilha Christmas', 'codigo_fone' => '61']);
		DB::table('paises')->insert(['codigo_iso2' => 'CC', 'codigo_iso3' => 'CCK', 'nome' => 'Ilhas Cocos (Keeling)', 'codigo_fone' => '672']);
		DB::table('paises')->insert(['codigo_iso2' => 'CO', 'codigo_iso3' => 'COL', 'nome' => 'Colômbia', 'codigo_fone' => '57']);
		DB::table('paises')->insert(['codigo_iso2' => 'KM', 'codigo_iso3' => 'COM', 'nome' => 'Comores', 'codigo_fone' => '269']);
		DB::table('paises')->insert(['codigo_iso2' => 'CG', 'codigo_iso3' => 'COG', 'nome' => 'Congo', 'codigo_fone' => '242']);
		DB::table('paises')->insert(['codigo_iso2' => 'CD', 'codigo_iso3' => 'COD', 'nome' => 'Congo (DR)', 'codigo_fone' => '242']);
		DB::table('paises')->insert(['codigo_iso2' => 'CK', 'codigo_iso3' => 'COK', 'nome' => 'Ilhas Cook', 'codigo_fone' => '682']);
		DB::table('paises')->insert(['codigo_iso2' => 'CR', 'codigo_iso3' => 'CRI', 'nome' => 'Costa Rica', 'codigo_fone' => '506']);
		DB::table('paises')->insert(['codigo_iso2' => 'CI', 'codigo_iso3' => 'CIV', 'nome' => 'Costa do Marfim', 'codigo_fone' => '225']);
		DB::table('paises')->insert(['codigo_iso2' => 'HR', 'codigo_iso3' => 'HRV', 'nome' => 'Croácia', 'codigo_fone' => '385']);
		DB::table('paises')->insert(['codigo_iso2' => 'CU', 'codigo_iso3' => 'CUB', 'nome' => 'Cuba', 'codigo_fone' => '53']);
		DB::table('paises')->insert(['codigo_iso2' => 'CY', 'codigo_iso3' => 'CYP', 'nome' => 'Chipre', 'codigo_fone' => '357']);
		DB::table('paises')->insert(['codigo_iso2' => 'CZ', 'codigo_iso3' => 'CZE', 'nome' => 'República Tcheca', 'codigo_fone' => '420']);
		DB::table('paises')->insert(['codigo_iso2' => 'DK', 'codigo_iso3' => 'DNK', 'nome' => 'Dinamarca', 'codigo_fone' => '45']);
		DB::table('paises')->insert(['codigo_iso2' => 'DJ', 'codigo_iso3' => 'DJI', 'nome' => 'Djibuti', 'codigo_fone' => '253']);
		DB::table('paises')->insert(['codigo_iso2' => 'DM', 'codigo_iso3' => 'DMA', 'nome' => 'Dominica', 'codigo_fone' => '1767']);
		DB::table('paises')->insert(['codigo_iso2' => 'DO', 'codigo_iso3' => 'DOM', 'nome' => 'República Dominicana', 'codigo_fone' => '1809']);
		DB::table('paises')->insert(['codigo_iso2' => 'EC', 'codigo_iso3' => 'ECU', 'nome' => 'Equador', 'codigo_fone' => '593']);
		DB::table('paises')->insert(['codigo_iso2' => 'EG', 'codigo_iso3' => 'EGY', 'nome' => 'Egito', 'codigo_fone' => '20']);
		DB::table('paises')->insert(['codigo_iso2' => 'SV', 'codigo_iso3' => 'SLV', 'nome' => 'El Salvador', 'codigo_fone' => '503']);
		DB::table('paises')->insert(['codigo_iso2' => 'GQ', 'codigo_iso3' => 'GNQ', 'nome' => 'Guiné Equatorial', 'codigo_fone' => '240']);
		DB::table('paises')->insert(['codigo_iso2' => 'ER', 'codigo_iso3' => 'ERI', 'nome' => 'Eritreia', 'codigo_fone' => '291']);
		DB::table('paises')->insert(['codigo_iso2' => 'EE', 'codigo_iso3' => 'EST', 'nome' => 'Estônia', 'codigo_fone' => '372']);
		DB::table('paises')->insert(['codigo_iso2' => 'ET', 'codigo_iso3' => 'ETH', 'nome' => 'Etiópia', 'codigo_fone' => '251']);
		DB::table('paises')->insert(['codigo_iso2' => 'FK', 'codigo_iso3' => 'FLK', 'nome' => 'Ilhas Malvinas', 'codigo_fone' => '500']);
		DB::table('paises')->insert(['codigo_iso2' => 'FO', 'codigo_iso3' => 'FRO', 'nome' => 'Ilhas Faroe', 'codigo_fone' => '298']);
		DB::table('paises')->insert(['codigo_iso2' => 'FJ', 'codigo_iso3' => 'FJI', 'nome' => 'Fiji', 'codigo_fone' => '679']);
		DB::table('paises')->insert(['codigo_iso2' => 'FI', 'codigo_iso3' => 'FIN', 'nome' => 'Finlândia', 'codigo_fone' => '358']);
		DB::table('paises')->insert(['codigo_iso2' => 'FR', 'codigo_iso3' => 'FRA', 'nome' => 'França', 'codigo_fone' => '33']);
		DB::table('paises')->insert(['codigo_iso2' => 'GF', 'codigo_iso3' => 'GUF', 'nome' => 'Guiana Francesa', 'codigo_fone' => '594']);
		DB::table('paises')->insert(['codigo_iso2' => 'PF', 'codigo_iso3' => 'PYF', 'nome' => 'Polinésia Francesa', 'codigo_fone' => '689']);
		DB::table('paises')->insert(['codigo_iso2' => 'TF', 'codigo_iso3' => 'ATF', 'nome' => 'Terras Austrais e Antárticas Francesas', 'codigo_fone' => '33']);
		DB::table('paises')->insert(['codigo_iso2' => 'GA', 'codigo_iso3' => 'GAB', 'nome' => 'Gabão', 'codigo_fone' => '241']);
		DB::table('paises')->insert(['codigo_iso2' => 'GM', 'codigo_iso3' => 'GMB', 'nome' => 'Gâmbia', 'codigo_fone' => '220']);
		DB::table('paises')->insert(['codigo_iso2' => 'GE', 'codigo_iso3' => 'GEO', 'nome' => 'Geórgia', 'codigo_fone' => '995']);
		DB::table('paises')->insert(['codigo_iso2' => 'DE', 'codigo_iso3' => 'DEU', 'nome' => 'Alemanha', 'codigo_fone' => '49']);
		DB::table('paises')->insert(['codigo_iso2' => 'GH', 'codigo_iso3' => 'GHA', 'nome' => 'Gana', 'codigo_fone' => '233']);
		DB::table('paises')->insert(['codigo_iso2' => 'GI', 'codigo_iso3' => 'GIB', 'nome' => 'Gibraltar', 'codigo_fone' => '350']);
		DB::table('paises')->insert(['codigo_iso2' => 'GR', 'codigo_iso3' => 'GRC', 'nome' => 'Grécia', 'codigo_fone' => '30']);
		DB::table('paises')->insert(['codigo_iso2' => 'GL', 'codigo_iso3' => 'GRL', 'nome' => 'Groelândia', 'codigo_fone' => '299']);
		DB::table('paises')->insert(['codigo_iso2' => 'GD', 'codigo_iso3' => 'GRD', 'nome' => 'Granada', 'codigo_fone' => '1473']);
		DB::table('paises')->insert(['codigo_iso2' => 'GP', 'codigo_iso3' => 'GLP', 'nome' => 'Guadalupe', 'codigo_fone' => '590']);
		DB::table('paises')->insert(['codigo_iso2' => 'GU', 'codigo_iso3' => 'GUM', 'nome' => 'Guão', 'codigo_fone' => '1671']);
		DB::table('paises')->insert(['codigo_iso2' => 'GT', 'codigo_iso3' => 'GTM', 'nome' => 'Guatemala', 'codigo_fone' => '502']);
		DB::table('paises')->insert(['codigo_iso2' => 'GN', 'codigo_iso3' => 'GIN', 'nome' => 'Guiné', 'codigo_fone' => '224']);
		DB::table('paises')->insert(['codigo_iso2' => 'GW', 'codigo_iso3' => 'GNB', 'nome' => 'Guiné-Bissau', 'codigo_fone' => '245']);
		DB::table('paises')->insert(['codigo_iso2' => 'GY', 'codigo_iso3' => 'GUY', 'nome' => 'Guiana', 'codigo_fone' => '592']);
		DB::table('paises')->insert(['codigo_iso2' => 'HT', 'codigo_iso3' => 'HTI', 'nome' => 'Haiti', 'codigo_fone' => '509']);
		DB::table('paises')->insert(['codigo_iso2' => 'HM', 'codigo_iso3' => 'HMD', 'nome' => 'Ilhas Heard e McDonald', 'codigo_fone' => '672']);
		DB::table('paises')->insert(['codigo_iso2' => 'VA', 'codigo_iso3' => 'VAT', 'nome' => 'Vaticano', 'codigo_fone' => '39']);
		DB::table('paises')->insert(['codigo_iso2' => 'HN', 'codigo_iso3' => 'HND', 'nome' => 'Honduras', 'codigo_fone' => '504']);
		DB::table('paises')->insert(['codigo_iso2' => 'HK', 'codigo_iso3' => 'HKG', 'nome' => 'Hong Kong', 'codigo_fone' => '852']);
		DB::table('paises')->insert(['codigo_iso2' => 'HU', 'codigo_iso3' => 'HUN', 'nome' => 'Hungria', 'codigo_fone' => '36']);
		DB::table('paises')->insert(['codigo_iso2' => 'IS', 'codigo_iso3' => 'ISL', 'nome' => 'Islândia', 'codigo_fone' => '354']);
		DB::table('paises')->insert(['codigo_iso2' => 'IN', 'codigo_iso3' => 'IND', 'nome' => 'Índia', 'codigo_fone' => '91']);
		DB::table('paises')->insert(['codigo_iso2' => 'ID', 'codigo_iso3' => 'IDN', 'nome' => 'Indonésia', 'codigo_fone' => '62']);
		DB::table('paises')->insert(['codigo_iso2' => 'IR', 'codigo_iso3' => 'IRN', 'nome' => 'Iran', 'codigo_fone' => '98']);
		DB::table('paises')->insert(['codigo_iso2' => 'IQ', 'codigo_iso3' => 'IRQ', 'nome' => 'Iraque', 'codigo_fone' => '964']);
		DB::table('paises')->insert(['codigo_iso2' => 'IE', 'codigo_iso3' => 'IRL', 'nome' => 'Irlanda', 'codigo_fone' => '353']);
		DB::table('paises')->insert(['codigo_iso2' => 'IL', 'codigo_iso3' => 'ISR', 'nome' => 'Israel', 'codigo_fone' => '972']);
		DB::table('paises')->insert(['codigo_iso2' => 'IT', 'codigo_iso3' => 'ITA', 'nome' => 'Italia', 'codigo_fone' => '39']);
		DB::table('paises')->insert(['codigo_iso2' => 'JM', 'codigo_iso3' => 'JAM', 'nome' => 'Jamaica', 'codigo_fone' => '1876']);
		DB::table('paises')->insert(['codigo_iso2' => 'JP', 'codigo_iso3' => 'JPN', 'nome' => 'Japão', 'codigo_fone' => '81']);
		DB::table('paises')->insert(['codigo_iso2' => 'JO', 'codigo_iso3' => 'JOR', 'nome' => 'Jornânia', 'codigo_fone' => '962']);
		DB::table('paises')->insert(['codigo_iso2' => 'KZ', 'codigo_iso3' => 'KAZ', 'nome' => 'Cazaquistão', 'codigo_fone' => '7']);
		DB::table('paises')->insert(['codigo_iso2' => 'KE', 'codigo_iso3' => 'KEN', 'nome' => 'Quênia', 'codigo_fone' => '254']);
		DB::table('paises')->insert(['codigo_iso2' => 'KI', 'codigo_iso3' => 'KIR', 'nome' => 'Kiribati', 'codigo_fone' => '686']);
		DB::table('paises')->insert(['codigo_iso2' => 'KP', 'codigo_iso3' => 'PRK', 'nome' => 'Coreia do Norte', 'codigo_fone' => '850']);
		DB::table('paises')->insert(['codigo_iso2' => 'KR', 'codigo_iso3' => 'KOR', 'nome' => 'Coreia do Sul', 'codigo_fone' => '82']);
		DB::table('paises')->insert(['codigo_iso2' => 'KW', 'codigo_iso3' => 'KWT', 'nome' => 'Kuwait', 'codigo_fone' => '965']);
		DB::table('paises')->insert(['codigo_iso2' => 'KG', 'codigo_iso3' => 'KGZ', 'nome' => 'Quirguistão', 'codigo_fone' => '996']);
		DB::table('paises')->insert(['codigo_iso2' => 'LA', 'codigo_iso3' => 'LAO', 'nome' => 'Laos', 'codigo_fone' => '856']);
		DB::table('paises')->insert(['codigo_iso2' => 'LV', 'codigo_iso3' => 'LVA', 'nome' => 'Letônia', 'codigo_fone' => '371']);
		DB::table('paises')->insert(['codigo_iso2' => 'LB', 'codigo_iso3' => 'LBN', 'nome' => 'Líbano', 'codigo_fone' => '961']);
		DB::table('paises')->insert(['codigo_iso2' => 'LS', 'codigo_iso3' => 'LSO', 'nome' => 'Lesoto', 'codigo_fone' => '266']);
		DB::table('paises')->insert(['codigo_iso2' => 'LR', 'codigo_iso3' => 'LBR', 'nome' => 'Libéria', 'codigo_fone' => '231']);
		DB::table('paises')->insert(['codigo_iso2' => 'LY', 'codigo_iso3' => 'LBY', 'nome' => 'Líbia', 'codigo_fone' => '218']);
		DB::table('paises')->insert(['codigo_iso2' => 'LI', 'codigo_iso3' => 'LIE', 'nome' => 'Liechtenstein', 'codigo_fone' => '423']);
		DB::table('paises')->insert(['codigo_iso2' => 'LT', 'codigo_iso3' => 'LTU', 'nome' => 'Lituânia', 'codigo_fone' => '370']);
		DB::table('paises')->insert(['codigo_iso2' => 'LU', 'codigo_iso3' => 'LUX', 'nome' => 'Luxemburgo', 'codigo_fone' => '352']);
		DB::table('paises')->insert(['codigo_iso2' => 'MO', 'codigo_iso3' => 'MAC', 'nome' => 'Macao', 'codigo_fone' => '853']);
		DB::table('paises')->insert(['codigo_iso2' => 'MK', 'codigo_iso3' => 'MKD', 'nome' => 'Macedônia', 'codigo_fone' => '389']);
		DB::table('paises')->insert(['codigo_iso2' => 'MG', 'codigo_iso3' => 'MDG', 'nome' => 'Madagascar', 'codigo_fone' => '261']);
		DB::table('paises')->insert(['codigo_iso2' => 'MW', 'codigo_iso3' => 'MWI', 'nome' => 'Malawi', 'codigo_fone' => '265']);
		DB::table('paises')->insert(['codigo_iso2' => 'MY', 'codigo_iso3' => 'MYS', 'nome' => 'Malásia', 'codigo_fone' => '60']);
		DB::table('paises')->insert(['codigo_iso2' => 'MV', 'codigo_iso3' => 'MDV', 'nome' => 'Maldivas', 'codigo_fone' => '960']);
		DB::table('paises')->insert(['codigo_iso2' => 'ML', 'codigo_iso3' => 'MLI', 'nome' => 'Mali', 'codigo_fone' => '223']);
		DB::table('paises')->insert(['codigo_iso2' => 'MT', 'codigo_iso3' => 'MLT', 'nome' => 'Malta', 'codigo_fone' => '356']);
		DB::table('paises')->insert(['codigo_iso2' => 'MH', 'codigo_iso3' => 'MHL', 'nome' => 'Ilhas Marshall', 'codigo_fone' => '692']);
		DB::table('paises')->insert(['codigo_iso2' => 'MQ', 'codigo_iso3' => 'MTQ', 'nome' => 'Martinica', 'codigo_fone' => '596']);
		DB::table('paises')->insert(['codigo_iso2' => 'MR', 'codigo_iso3' => 'MRT', 'nome' => 'Mauritânia', 'codigo_fone' => '222']);
		DB::table('paises')->insert(['codigo_iso2' => 'MU', 'codigo_iso3' => 'MUS', 'nome' => 'Maurício', 'codigo_fone' => '230']);
		DB::table('paises')->insert(['codigo_iso2' => 'YT', 'codigo_iso3' => 'MYT', 'nome' => 'Mayotte', 'codigo_fone' => '269']);
		DB::table('paises')->insert(['codigo_iso2' => 'MX', 'codigo_iso3' => 'MEX', 'nome' => 'México', 'codigo_fone' => '52']);
		DB::table('paises')->insert(['codigo_iso2' => 'FM', 'codigo_iso3' => 'FSM', 'nome' => 'Micronésia', 'codigo_fone' => '691']);
		DB::table('paises')->insert(['codigo_iso2' => 'MD', 'codigo_iso3' => 'MDA', 'nome' => 'Moldova', 'codigo_fone' => '373']);
		DB::table('paises')->insert(['codigo_iso2' => 'MC', 'codigo_iso3' => 'MCO', 'nome' => 'Mônaco', 'codigo_fone' => '377']);
		DB::table('paises')->insert(['codigo_iso2' => 'MN', 'codigo_iso3' => 'MNG', 'nome' => 'Mongólia', 'codigo_fone' => '976']);
		DB::table('paises')->insert(['codigo_iso2' => 'MS', 'codigo_iso3' => 'MSR', 'nome' => 'Montserrat', 'codigo_fone' => '1664']);
		DB::table('paises')->insert(['codigo_iso2' => 'MA', 'codigo_iso3' => 'MAR', 'nome' => 'Marrocos', 'codigo_fone' => '212']);
		DB::table('paises')->insert(['codigo_iso2' => 'MZ', 'codigo_iso3' => 'MOZ', 'nome' => 'Moçambique', 'codigo_fone' => '258']);
		DB::table('paises')->insert(['codigo_iso2' => 'MM', 'codigo_iso3' => 'MMR', 'nome' => 'Birmânia', 'codigo_fone' => '95']);
		DB::table('paises')->insert(['codigo_iso2' => 'NA', 'codigo_iso3' => 'NAM', 'nome' => 'Namíbia', 'codigo_fone' => '264']);
		DB::table('paises')->insert(['codigo_iso2' => 'NR', 'codigo_iso3' => 'NRU', 'nome' => 'Nauru', 'codigo_fone' => '674']);
		DB::table('paises')->insert(['codigo_iso2' => 'NP', 'codigo_iso3' => 'NPL', 'nome' => 'Nepal', 'codigo_fone' => '977']);
		DB::table('paises')->insert(['codigo_iso2' => 'NL', 'codigo_iso3' => 'NLD', 'nome' => 'Holanda', 'codigo_fone' => '31']);
		DB::table('paises')->insert(['codigo_iso2' => 'AN', 'codigo_iso3' => 'ANT', 'nome' => 'Antilhas Holandesas', 'codigo_fone' => '599']);
		DB::table('paises')->insert(['codigo_iso2' => 'NC', 'codigo_iso3' => 'NCL', 'nome' => 'Nova Caledônia', 'codigo_fone' => '687']);
		DB::table('paises')->insert(['codigo_iso2' => 'NZ', 'codigo_iso3' => 'NZL', 'nome' => 'Nova Zelândia', 'codigo_fone' => '64']);
		DB::table('paises')->insert(['codigo_iso2' => 'NI', 'codigo_iso3' => 'NIC', 'nome' => 'Nicarágua', 'codigo_fone' => '505']);
		DB::table('paises')->insert(['codigo_iso2' => 'NE', 'codigo_iso3' => 'NER', 'nome' => 'Niger', 'codigo_fone' => '227']);
		DB::table('paises')->insert(['codigo_iso2' => 'NG', 'codigo_iso3' => 'NGA', 'nome' => 'Nigéria', 'codigo_fone' => '234']);
		DB::table('paises')->insert(['codigo_iso2' => 'NU', 'codigo_iso3' => 'NIU', 'nome' => 'Niue', 'codigo_fone' => '683']);
		DB::table('paises')->insert(['codigo_iso2' => 'NF', 'codigo_iso3' => 'NFK', 'nome' => 'Ilha Norfolk', 'codigo_fone' => '672']);
		DB::table('paises')->insert(['codigo_iso2' => 'MP', 'codigo_iso3' => 'MNP', 'nome' => 'Ilhas Marianas do Norte', 'codigo_fone' => '1670']);
		DB::table('paises')->insert(['codigo_iso2' => 'NO', 'codigo_iso3' => 'NOR', 'nome' => 'Noruega', 'codigo_fone' => '47']);
		DB::table('paises')->insert(['codigo_iso2' => 'OM', 'codigo_iso3' => 'OMN', 'nome' => 'Omã', 'codigo_fone' => '968']);
		DB::table('paises')->insert(['codigo_iso2' => 'PK', 'codigo_iso3' => 'PAK', 'nome' => 'Paquistão', 'codigo_fone' => '92']);
		DB::table('paises')->insert(['codigo_iso2' => 'PW', 'codigo_iso3' => 'PLW', 'nome' => 'Palau', 'codigo_fone' => '680']);
		DB::table('paises')->insert(['codigo_iso2' => 'PS', 'codigo_iso3' => 'PSE', 'nome' => 'Palestina', 'codigo_fone' => '970']);
		DB::table('paises')->insert(['codigo_iso2' => 'PA', 'codigo_iso3' => 'PAN', 'nome' => 'Panamá', 'codigo_fone' => '507']);
		DB::table('paises')->insert(['codigo_iso2' => 'PG', 'codigo_iso3' => 'PNG', 'nome' => 'Papua-Nova Guiné', 'codigo_fone' => '675']);
		DB::table('paises')->insert(['codigo_iso2' => 'PY', 'codigo_iso3' => 'PRY', 'nome' => 'Paraguai', 'codigo_fone' => '595']);
		DB::table('paises')->insert(['codigo_iso2' => 'PE', 'codigo_iso3' => 'PER', 'nome' => 'Peru', 'codigo_fone' => '51']);
		DB::table('paises')->insert(['codigo_iso2' => 'PH', 'codigo_iso3' => 'PHL', 'nome' => 'Filipinas', 'codigo_fone' => '63']);
		DB::table('paises')->insert(['codigo_iso2' => 'PN', 'codigo_iso3' => 'PCN', 'nome' => 'Ilhas Picárnia', 'codigo_fone' => '672']);
		DB::table('paises')->insert(['codigo_iso2' => 'PL', 'codigo_iso3' => 'POL', 'nome' => 'Polônia', 'codigo_fone' => '48']);
		DB::table('paises')->insert(['codigo_iso2' => 'PT', 'codigo_iso3' => 'PRT', 'nome' => 'Portugal', 'codigo_fone' => '351']);
		DB::table('paises')->insert(['codigo_iso2' => 'PR', 'codigo_iso3' => 'PRI', 'nome' => 'Porto Rico', 'codigo_fone' => '1787']);
		DB::table('paises')->insert(['codigo_iso2' => 'QA', 'codigo_iso3' => 'QAT', 'nome' => 'Catar', 'codigo_fone' => '974']);
		DB::table('paises')->insert(['codigo_iso2' => 'RE', 'codigo_iso3' => 'REU', 'nome' => 'Reunião', 'codigo_fone' => '262']);
		DB::table('paises')->insert(['codigo_iso2' => 'RO', 'codigo_iso3' => 'ROM', 'nome' => 'Romênia', 'codigo_fone' => '40']);
		DB::table('paises')->insert(['codigo_iso2' => 'RU', 'codigo_iso3' => 'RUS', 'nome' => 'Rússia', 'codigo_fone' => '70']);
		DB::table('paises')->insert(['codigo_iso2' => 'RW', 'codigo_iso3' => 'RWA', 'nome' => 'Ruanda', 'codigo_fone' => '250']);
		DB::table('paises')->insert(['codigo_iso2' => 'SH', 'codigo_iso3' => 'SHN', 'nome' => 'Santa Helena', 'codigo_fone' => '290']);
		DB::table('paises')->insert(['codigo_iso2' => 'KN', 'codigo_iso3' => 'KNA', 'nome' => 'São Cristóvão', 'codigo_fone' => '1869']);
		DB::table('paises')->insert(['codigo_iso2' => 'LC', 'codigo_iso3' => 'LCA', 'nome' => 'Santa Lúcia', 'codigo_fone' => '1758']);
		DB::table('paises')->insert(['codigo_iso2' => 'PM', 'codigo_iso3' => 'SPM', 'nome' => 'São Pedro e Miquelon', 'codigo_fone' => '508']);
		DB::table('paises')->insert(['codigo_iso2' => 'VC', 'codigo_iso3' => 'VCT', 'nome' => 'São Vicente e Granadinas', 'codigo_fone' => '1784']);
		DB::table('paises')->insert(['codigo_iso2' => 'WS', 'codigo_iso3' => 'WSM', 'nome' => 'Samoa', 'codigo_fone' => '684']);
		DB::table('paises')->insert(['codigo_iso2' => 'SM', 'codigo_iso3' => 'SMR', 'nome' => 'São Marino', 'codigo_fone' => '378']);
		DB::table('paises')->insert(['codigo_iso2' => 'ST', 'codigo_iso3' => 'STP', 'nome' => 'Sao Tomé e Príncipe', 'codigo_fone' => '239']);
		DB::table('paises')->insert(['codigo_iso2' => 'SA', 'codigo_iso3' => 'SAU', 'nome' => 'Arábia Saudita', 'codigo_fone' => '966']);
		DB::table('paises')->insert(['codigo_iso2' => 'SN', 'codigo_iso3' => 'SEN', 'nome' => 'Senegal', 'codigo_fone' => '221']);
		DB::table('paises')->insert(['codigo_iso2' => 'CS', 'codigo_iso3' => 'SRB', 'nome' => 'Sérvia e Montenegro', 'codigo_fone' => '381']);
		DB::table('paises')->insert(['codigo_iso2' => 'SC', 'codigo_iso3' => 'SYC', 'nome' => 'Seicheles', 'codigo_fone' => '248']);
		DB::table('paises')->insert(['codigo_iso2' => 'SL', 'codigo_iso3' => 'SLE', 'nome' => 'República da Serra Leoa', 'codigo_fone' => '232']);
		DB::table('paises')->insert(['codigo_iso2' => 'SG', 'codigo_iso3' => 'SGP', 'nome' => 'Singapura', 'codigo_fone' => '65']);
		DB::table('paises')->insert(['codigo_iso2' => 'SK', 'codigo_iso3' => 'SVK', 'nome' => 'Eslováquia', 'codigo_fone' => '421']);
		DB::table('paises')->insert(['codigo_iso2' => 'SI', 'codigo_iso3' => 'SVN', 'nome' => 'Eslovênia', 'codigo_fone' => '386']);
		DB::table('paises')->insert(['codigo_iso2' => 'SB', 'codigo_iso3' => 'SLB', 'nome' => 'Ilhas Salomão', 'codigo_fone' => '677']);
		DB::table('paises')->insert(['codigo_iso2' => 'SO', 'codigo_iso3' => 'SOM', 'nome' => 'Somália', 'codigo_fone' => '252']);
		DB::table('paises')->insert(['codigo_iso2' => 'ZA', 'codigo_iso3' => 'ZAF', 'nome' => 'África do Sul', 'codigo_fone' => '27']);
		DB::table('paises')->insert(['codigo_iso2' => 'GS', 'codigo_iso3' => 'SGS', 'nome' => 'Ilhas Geórgia do Sul e Sandwich do Sul', 'codigo_fone' => '500']);
		DB::table('paises')->insert(['codigo_iso2' => 'ES', 'codigo_iso3' => 'ESP', 'nome' => 'Espanha', 'codigo_fone' => '34']);
		DB::table('paises')->insert(['codigo_iso2' => 'LK', 'codigo_iso3' => 'LKA', 'nome' => 'Sri Lanka', 'codigo_fone' => '94']);
		DB::table('paises')->insert(['codigo_iso2' => 'SD', 'codigo_iso3' => 'SDN', 'nome' => 'Sudão', 'codigo_fone' => '249']);
		DB::table('paises')->insert(['codigo_iso2' => 'SR', 'codigo_iso3' => 'SUR', 'nome' => 'Suriname', 'codigo_fone' => '597']);
		DB::table('paises')->insert(['codigo_iso2' => 'SJ', 'codigo_iso3' => 'SJM', 'nome' => 'Esvalbarde', 'codigo_fone' => '47']);
		DB::table('paises')->insert(['codigo_iso2' => 'SZ', 'codigo_iso3' => 'SWZ', 'nome' => 'Suazilândia', 'codigo_fone' => '268']);
		DB::table('paises')->insert(['codigo_iso2' => 'SE', 'codigo_iso3' => 'SWE', 'nome' => 'Suécia', 'codigo_fone' => '46']);
		DB::table('paises')->insert(['codigo_iso2' => 'CH', 'codigo_iso3' => 'CHE', 'nome' => 'Suiça', 'codigo_fone' => '41']);
		DB::table('paises')->insert(['codigo_iso2' => 'SY', 'codigo_iso3' => 'SYR', 'nome' => 'Síria', 'codigo_fone' => '963']);
		DB::table('paises')->insert(['codigo_iso2' => 'TW', 'codigo_iso3' => 'TWN', 'nome' => 'Taiwan', 'codigo_fone' => '886']);
		DB::table('paises')->insert(['codigo_iso2' => 'TJ', 'codigo_iso3' => 'TJK', 'nome' => 'Tajiquistão', 'codigo_fone' => '992']);
		DB::table('paises')->insert(['codigo_iso2' => 'TZ', 'codigo_iso3' => 'TZA', 'nome' => 'Tanzânia', 'codigo_fone' => '255']);
		DB::table('paises')->insert(['codigo_iso2' => 'TH', 'codigo_iso3' => 'THA', 'nome' => 'Tailândia', 'codigo_fone' => '66']);
		DB::table('paises')->insert(['codigo_iso2' => 'TL', 'codigo_iso3' => 'TLS', 'nome' => 'Timor-Leste', 'codigo_fone' => '670']);
		DB::table('paises')->insert(['codigo_iso2' => 'TG', 'codigo_iso3' => 'TGO', 'nome' => 'Togo', 'codigo_fone' => '228']);
		DB::table('paises')->insert(['codigo_iso2' => 'TK', 'codigo_iso3' => 'TKL', 'nome' => 'Toquelau', 'codigo_fone' => '690']);
		DB::table('paises')->insert(['codigo_iso2' => 'TO', 'codigo_iso3' => 'TON', 'nome' => 'Tonga', 'codigo_fone' => '676']);
		DB::table('paises')->insert(['codigo_iso2' => 'TT', 'codigo_iso3' => 'TTO', 'nome' => 'Trinidad e Tobago', 'codigo_fone' => '1868']);
		DB::table('paises')->insert(['codigo_iso2' => 'TN', 'codigo_iso3' => 'TUN', 'nome' => 'Tunísia', 'codigo_fone' => '216']);
		DB::table('paises')->insert(['codigo_iso2' => 'TR', 'codigo_iso3' => 'TUR', 'nome' => 'Turquia', 'codigo_fone' => '90']);
		DB::table('paises')->insert(['codigo_iso2' => 'TM', 'codigo_iso3' => 'TKM', 'nome' => 'Turcomenistão', 'codigo_fone' => '7370']);
		DB::table('paises')->insert(['codigo_iso2' => 'TC', 'codigo_iso3' => 'TCA', 'nome' => 'Ilhas Turks e Caicos', 'codigo_fone' => '1649']);
		DB::table('paises')->insert(['codigo_iso2' => 'TV', 'codigo_iso3' => 'TUV', 'nome' => 'Tuvalu', 'codigo_fone' => '688']);
		DB::table('paises')->insert(['codigo_iso2' => 'UG', 'codigo_iso3' => 'UGA', 'nome' => 'Uganda', 'codigo_fone' => '256']);
		DB::table('paises')->insert(['codigo_iso2' => 'UA', 'codigo_iso3' => 'UKR', 'nome' => 'Ucrânia', 'codigo_fone' => '380']);
		DB::table('paises')->insert(['codigo_iso2' => 'AE', 'codigo_iso3' => 'ARE', 'nome' => 'Emirados Árabes', 'codigo_fone' => '971']);
		DB::table('paises')->insert(['codigo_iso2' => 'GB', 'codigo_iso3' => 'GBR', 'nome' => 'Reino Unido', 'codigo_fone' => '44']);
		DB::table('paises')->insert(['codigo_iso2' => 'US', 'codigo_iso3' => 'USA', 'nome' => 'Estados Unidos', 'codigo_fone' => '1']);
		DB::table('paises')->insert(['codigo_iso2' => 'UM', 'codigo_iso3' => 'UMI', 'nome' => 'Ilhas Menores Distantes dos Estados Unidos', 'codigo_fone' => '1']);
		DB::table('paises')->insert(['codigo_iso2' => 'UY', 'codigo_iso3' => 'URY', 'nome' => 'Uruguai', 'codigo_fone' => '598']);
		DB::table('paises')->insert(['codigo_iso2' => 'UZ', 'codigo_iso3' => 'UZB', 'nome' => 'Uzbequistão', 'codigo_fone' => '998']);
		DB::table('paises')->insert(['codigo_iso2' => 'VU', 'codigo_iso3' => 'VUT', 'nome' => 'Vanuatu', 'codigo_fone' => '678']);
		DB::table('paises')->insert(['codigo_iso2' => 'VE', 'codigo_iso3' => 'VEN', 'nome' => 'Venezuela', 'codigo_fone' => '58']);
		DB::table('paises')->insert(['codigo_iso2' => 'VN', 'codigo_iso3' => 'VNM', 'nome' => 'Vietnam', 'codigo_fone' => '84']);
		DB::table('paises')->insert(['codigo_iso2' => 'VG', 'codigo_iso3' => 'VGB', 'nome' => 'Ilhas Virgens Inglesas', 'codigo_fone' => '1284']);
		DB::table('paises')->insert(['codigo_iso2' => 'VI', 'codigo_iso3' => 'VIR', 'nome' => 'Ilhas Virgens (USA)', 'codigo_fone' => '1340']);
		DB::table('paises')->insert(['codigo_iso2' => 'WF', 'codigo_iso3' => 'WLF', 'nome' => 'Wallis e Futuna', 'codigo_fone' => '681']);
		DB::table('paises')->insert(['codigo_iso2' => 'EH', 'codigo_iso3' => 'ESH', 'nome' => 'Saara Ocidental', 'codigo_fone' => '212']);
		DB::table('paises')->insert(['codigo_iso2' => 'YE', 'codigo_iso3' => 'YEM', 'nome' => 'Iêmen', 'codigo_fone' => '967']);
		DB::table('paises')->insert(['codigo_iso2' => 'ZM', 'codigo_iso3' => 'ZMB', 'nome' => 'Zâmbia', 'codigo_fone' => '260']);
		DB::table('paises')->insert(['codigo_iso2' => 'ZW', 'codigo_iso3' => 'ZWE', 'nome' => 'Zimbábue', 'codigo_fone' => '263']);
    }
}
