---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/nossolaralorg/public_html/comunidadenossolar/
    #sรณ pega a primeira linha de comando!!!!
    #- /bin/cp public/* $DEPLOYPATH #copia todos os arquivos da pasta public (sem as pastas)
    #- /bin/cp public/css/* $DEPLOYPATH #copia todos os arquivos da pasta css
    - /bin/cp public/-r * $DEPLOYPATH
