---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/nossolaralorg/public_html/comunidadenossolar/
    #- /bin/cp * $DEPLOYPATH essa linha dรก certo
    - /bin/cp public/* $DEPLOYPATH #copia todos os arquivos da pasta public (sem as pastas)
    - /bin/cp 'public/css/' * $DEPLOYPATH #copia todos os arquivos da pasta public (sem as pastas)
    #- /bin/cp public/ -r * $DEPLOYPATH copia todas as pastas do root
