---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/nossolaralorg/public_html/comunidadenossolar/
    #- /bin/cp * $DEPLOYPATH essa linha dรก certo
    #- /bin/cp public/* $DEPLOYPATH essa tb
    #- /bin/cp public/ -r * $DEPLOYPATH copia todas as pastas do root
    - /bin/cp /public/-r * $DEPLOYPATH